openapi: '3.0.0'
info:
  title: Food Delivery API
  description: REST API for food delivery app with dynamic pricing module
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /pricing/calculate-price:
    post:
      summary: Calculate delivery cost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organization_id:
                  type: string
                zone:
                  type: string
                total_distance:
                  type: number
                item_type:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_price:
                    type: number
        '500':
          description: Internal Server Error
